#                 _     _     _
#                | |   | |   (_)
#    ___    ___  | |_  | |_   _   _ __     __ _   ___
#   / __|  / _ \ | __| | __| | | | '_ \   / _` | / __|
#   \__ \ |  __/ | |_  | |_  | | | | | | | (_| | \__ \
#   |___/  \___|  \__|  \__| |_| |_| |_|  \__, | |___/
#                                          __/ |
#                                         |___/
#

generate_date:

#是否启用饰品栏 (需要重启)
accessory_slot:
  enable: false #true 启用demo饰品栏

